name: Deploy RDS Infrastructure

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Set up AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      run: |
        echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
        echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV

    # --------------------------
    # Etapa 1: criar o bucket S3 via backend local/temporário
    # --------------------------
    - name: Terraform Init (local)
      run: terraform init -backend=false

    - name: Terraform Apply Bucket
      run: terraform apply -auto-approve -target=aws_s3_bucket.terraform_state_bucket
      env:
        TF_VAR_db_password: ${{ secrets.AWS_SECRET_DB_PASS }}

    # --------------------------
    # Etapa 2: "Ativar" o backend S3 e recriar o .tfstate lá
    # --------------------------
    - name: Enable remote backend
      run: |
        mv backend-remote.tf backend.tf  # rename ou copie para 'backend.tf'
        ls -l    

    - name: Terraform Init
      # run: terraform init
      run: terraform init -reconfigure

    - name: Terraform Validate
      run: terraform validate

    # Se quiser exibir o plano antes de aplicar, descomente:
    # - name: Terraform Plan
    #   run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_VAR_db_password: ${{ secrets.AWS_SECRET_DB_PASS }}

    # Exemplo de passo para criar database/tables via script SQL (opcional):
    - name: Install MySQL Client
      run: sudo apt-get update && sudo apt-get install -y mysql-client

    - name: Create Application Database
      run: |
        echo "Waiting for RDS to be available..."
        sleep 120  # Aguarda 2 minutos para garantir que o RDS esteja pronto

        mysql -h $(terraform output -raw db_endpoint) \
              -u $(terraform output -raw db_username) \
              -p"${{ secrets.AWS_SECRET_DB_PASS }}" \
              < scripts/setup_database.sql
